controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

admin_event_list:
    path: /admin/event
    controller: App\Controller\Admin\EventCrudController::index

admin_category_list:
    path: /admin/category
    controller: App\Controller\Admin\CategoryCrudController::index

admin_ambiance_list:
    path: /admin/ambiance
    controller: App\Controller\Admin\AmbianceCrudController::index

admin_specialRegime_list:
    path: /admin/specialRegime
    controller: App\Controller\Admin\SpecialRegimeCrudController::index