controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

admin_category_list:
    path: /admin/category
    controller: App\Controller\Admin\CategoryCrudController::index